export const SELECT_COURSE_FORM     = "SELECT_COURSE_FORM"
export const SELECT_SECTION_FORM    = "SELECT_SECTION_FORM"
export const SELECT_VIDEO_FORM      = "SELECT_VIDEO_FORM"
export const SELECT_INSTRUCTOR_FORM = "SELECT_INSTRUCTOR_FORM"