export const COMENTARIOS          = "COMENTARIOS"; 
export const MATERIALES           = "MATERIALES";
export const PARTICIPANTES        = "PARTICIPANTES"; 
export const PREGUNTAS_FRECUENTES = "PREGUNTAS FRECUENTES"; 
export const VER_TEMARIO          = "VER TEMARIO"; 
export const SOBRE_EL_INSTRUCTOR  = "SOBRE EL INSTRUCTOR"; 
export const DESCARGA_CERTIFICADO = "DESCARGA_CERTIFICADO"