//---- GET
export const GET_COURSE_DETAIL         = "GET_COURSE_DETAIL";
export const GET_INSTRUCTOR_BY_ID      = "GET_INSTRUCTOR_BY_ID";
export const GET_REVIEWS_BY_COURSE_ID  = "GET_REVIEWS_BY_COURSE_ID";
export const GET_SECTIONS_BY_COURSE_ID = "GET_SECTIONS_BY_COURSE_ID";
export const GET_USERS_BY_COURSE_ID    = "GET_USERS_BY_COURSE_ID";
export const GET_VIDEO_BY_ID           = "GET_VIDEO_BY_ID";

//POST 
export const CREATE_REVIEW = "CREATE_REVIEW";